name: 'Jira Login'
description: 'Log in to Jira Cloud instance'
branding:
  icon: 'log-in'
  color: 'blue'
inputs:
  issue:
    description: Key of the issue to be commented on
    required: true
  comment:
    description: Comment
    required: true
runs:
  using: 'node12'
  main: './dist/index.js'
